export const engineeringEnglishCards = [
  { question: "specify", answer: "指定する / 明示する" },
  { question: "require", answer: "必要とする" },
  { question: "provide", answer: "提供する" },
  { question: "support", answer: "対応する / サポートする" },
  { question: "allow", answer: "許可する" },
  { question: "enable", answer: "有効にする" },
  { question: "disable", answer: "無効にする" },
  { question: "configure", answer: "設定する" },
  { question: "install", answer: "インストールする" },
  { question: "setup", answer: "セットアップする" },

  { question: "define", answer: "定義する" },
  { question: "declare", answer: "宣言する" },
  { question: "initialize", answer: "初期化する" },
  { question: "execute", answer: "実行する" },
  { question: "implement", answer: "実装する" },
  { question: "handle", answer: "処理する" },
  { question: "process", answer: "処理する" },
  { question: "trigger", answer: "トリガーする" },
  { question: "invoke", answer: "呼び出す" },
  { question: "return", answer: "返す / 戻す" },

  { question: "retrieve", answer: "取得する" },
  { question: "fetch", answer: "取得する" },
  { question: "store", answer: "保存する" },
  { question: "update", answer: "更新する" },
  { question: "delete", answer: "削除する" },
  { question: "insert", answer: "挿入する" },
  { question: "remove", answer: "取り除く" },
  { question: "replace", answer: "置き換える" },
  { question: "append", answer: "追加する" },
  { question: "merge", answer: "統合する" },

  { question: "include", answer: "含む" },
  { question: "exclude", answer: "除外する" },
  { question: "contain", answer: "含んでいる" },
  { question: "consist", answer: "構成される" },
  { question: "represent", answer: "表す" },
  { question: "indicate", answer: "示す" },
  { question: "describe", answer: "説明する" },
  { question: "refer", answer: "参照する" },
  { question: "apply", answer: "適用する" },
  { question: "extend", answer: "拡張する" },

  { question: "override", answer: "上書きする" },
  { question: "expose", answer: "公開する" },
  { question: "generate", answer: "生成する" },
  { question: "create", answer: "作成する" },
  { question: "build", answer: "構築する" },
  { question: "compile", answer: "コンパイルする" },
  { question: "load", answer: "読み込む" },
  { question: "resolve", answer: "解決する" },
  { question: "determine", answer: "決定する" },
  { question: "ensure", answer: "確実にする" },

  { question: "prevent", answer: "防ぐ" },
  { question: "avoid", answer: "避ける" },
  { question: "verify", answer: "検証する" },
  { question: "validate", answer: "妥当性を確認する" },
  { question: "assume", answer: "仮定する" },
  { question: "consider", answer: "考慮する" },
  { question: "check", answer: "確認する" },
  { question: "monitor", answer: "監視する" },
  { question: "log", answer: "ログを記録する" },
  { question: "track", answer: "追跡する" },

  { question: "maintain", answer: "維持する" },
  { question: "improve", answer: "改善する" },
  { question: "optimize", answer: "最適化する" },
  { question: "refactor", answer: "リファクタリングする" },
  { question: "simplify", answer: "簡略化する" },
  { question: "reduce", answer: "減らす" },
  { question: "increase", answer: "増やす" },
  { question: "limit", answer: "制限する" },
  { question: "restrict", answer: "制限する" },
  { question: "control", answer: "制御する" },

  { question: "manage", answer: "管理する" },
  { question: "organize", answer: "整理する" },
  { question: "structure", answer: "構造化する" },
  { question: "separate", answer: "分離する" },
  { question: "combine", answer: "結合する" },
  { question: "connect", answer: "接続する" },
  { question: "link", answer: "リンクする" },
  { question: "bind", answer: "バインドする" },
  { question: "attach", answer: "取り付ける" },
  { question: "detach", answer: "切り離す" },

  { question: "access", answer: "アクセスする" },
  { question: "protect", answer: "保護する" },
  { question: "secure", answer: "安全にする" },
  { question: "encrypt", answer: "暗号化する" },
  { question: "decrypt", answer: "復号する" },
  { question: "authorize", answer: "認可する" },
  { question: "authenticate", answer: "認証する" },
  { question: "permit", answer: "許可する" },
  { question: "deny", answer: "拒否する" },
  { question: "deploy", answer: "デプロイする / 本番環境に反映する" },

  { question: "allocate", answer: "割り当てる" },
  { question: "release", answer: "解放する" },
  { question: "persist", answer: "永続化する" },
  { question: "propagate", answer: "伝播させる" },
  { question: "transform", answer: "変換する" },
  { question: "serialize", answer: "シリアライズする" },
  { question: "deserialize", answer: "デシリアライズする" },
  { question: "sanitize", answer: "サニタイズする" },
  { question: "throttle", answer: "処理頻度を制限する" },
  { question: "debounce", answer: "連続処理を抑制する" }
]