export const spanishBasicCards = [
{ question: "hola", answer: "こんにちは", description: "Hola, ¿cómo estás?" },
{ question: "adiós", answer: "さようなら", description: "Adiós, hasta mañana." },
{ question: "gracias", answer: "ありがとう", description: "Muchas gracias por tu ayuda." },
{ question: "por favor", answer: "お願いします", description: "Un café, por favor." },
{ question: "sí", answer: "はい", description: "Sí, claro." },
{ question: "no", answer: "いいえ", description: "No, gracias." },
{ question: "perdón", answer: "すみません", description: "Perdón, ¿dónde está el baño?" },
{ question: "lo siento", answer: "ごめんなさい", description: "Lo siento mucho." },
{ question: "bien", answer: "元気、良い", description: "Estoy bien hoy." },
{ question: "mal", answer: "悪い", description: "Me siento mal hoy." },

{ question: "amigo", answer: "友達", description: "Juan es mi amigo." },
{ question: "familia", answer: "家族", description: "Mi familia vive en Madrid." },
{ question: "madre", answer: "母", description: "Mi madre trabaja aquí." },
{ question: "padre", answer: "父", description: "Mi padre es profesor." },
{ question: "hermano", answer: "兄弟", description: "Tengo un hermano." },
{ question: "hermana", answer: "姉妹", description: "Mi hermana vive en España." },
{ question: "niño", answer: "男の子", description: "El niño juega en el parque." },
{ question: "niña", answer: "女の子", description: "La niña está en la escuela." },
{ question: "persona", answer: "人", description: "Es una buena persona." },
{ question: "gente", answer: "人々", description: "Hay mucha gente aquí." },

{ question: "casa", answer: "家", description: "Mi casa es pequeña." },
{ question: "habitación", answer: "部屋", description: "Mi habitación es grande." },
{ question: "puerta", answer: "ドア", description: "Cierra la puerta." },
{ question: "ventana", answer: "窓", description: "Abre la ventana." },
{ question: "mesa", answer: "机", description: "El libro está sobre la mesa." },
{ question: "silla", answer: "椅子", description: "La silla es cómoda." },
{ question: "cama", answer: "ベッド", description: "La cama está en la habitación." },
{ question: "calle", answer: "通り", description: "La calle está llena." },
{ question: "ciudad", answer: "街", description: "La ciudad es grande." },
{ question: "país", answer: "国", description: "España es un país bonito." },

{ question: "agua", answer: "水", description: "Bebo agua todos los días." },
{ question: "pan", answer: "パン", description: "Compro pan en la tienda." },
{ question: "comida", answer: "食べ物", description: "La comida está deliciosa." },
{ question: "bebida", answer: "飲み物", description: "Esta bebida está fría." },
{ question: "café", answer: "コーヒー", description: "Tomo café por la mañana." },
{ question: "leche", answer: "牛乳", description: "Bebo leche todos los días." },
{ question: "cerveza", answer: "ビール", description: "Tomamos cerveza en el bar." },
{ question: "vino", answer: "ワイン", description: "El vino es muy bueno." },
{ question: "manzana", answer: "りんご", description: "Como una manzana." },
{ question: "naranja", answer: "オレンジ", description: "La naranja es dulce." },

{ question: "desayuno", answer: "朝食", description: "El desayuno es a las ocho." },
{ question: "almuerzo", answer: "昼食", description: "Almuerzo con mis amigos." },
{ question: "cena", answer: "夕食", description: "La cena está lista." },
{ question: "restaurante", answer: "レストラン", description: "Vamos al restaurante." },
{ question: "tienda", answer: "店", description: "La tienda abre a las nueve." },
{ question: "escuela", answer: "学校", description: "La escuela está lejos." },
{ question: "trabajo", answer: "仕事", description: "Tengo mucho trabajo." },
{ question: "oficina", answer: "オフィス", description: "La oficina está cerrada." },
{ question: "coche", answer: "車", description: "El coche es nuevo." },
{ question: "tren", answer: "電車", description: "El tren llega pronto." },

{ question: "avión", answer: "飛行機", description: "El avión despega ahora." },
{ question: "tiempo", answer: "時間", description: "No tengo tiempo." },
{ question: "día", answer: "日", description: "Hoy es un buen día." },
{ question: "semana", answer: "週", description: "Trabajo cinco días a la semana." },
{ question: "mes", answer: "月", description: "Este mes viajo a España." },
{ question: "año", answer: "年", description: "Este año estudio español." },
{ question: "hoy", answer: "今日", description: "Hoy hace calor." },
{ question: "mañana", answer: "明日", description: "Mañana voy a trabajar." },
{ question: "ayer", answer: "昨日", description: "Ayer llovió mucho." },
{ question: "ahora", answer: "今", description: "Ahora estoy ocupado." },

{ question: "siempre", answer: "いつも", description: "Siempre estudio español." },
{ question: "nunca", answer: "決して〜ない", description: "Nunca bebo café." },
{ question: "mucho", answer: "たくさん", description: "Tengo mucho trabajo." },
{ question: "poco", answer: "少し", description: "Tengo poco tiempo." },
{ question: "todo", answer: "すべて", description: "Todo está bien." },
{ question: "nada", answer: "何も〜ない", description: "No veo nada." },
{ question: "algo", answer: "何か", description: "Quiero comer algo." },
{ question: "otro", answer: "別の", description: "Quiero otro café." },

{ question: "grande", answer: "大きい", description: "La casa es grande." },
{ question: "pequeño", answer: "小さい", description: "El perro es pequeño." },
{ question: "bueno", answer: "良い", description: "El libro es bueno." },
{ question: "malo", answer: "悪い", description: "El clima es malo." },
{ question: "nuevo", answer: "新しい", description: "El coche es nuevo." },
{ question: "viejo", answer: "古い", description: "Ese edificio es viejo." },
{ question: "bonito", answer: "きれい", description: "La ciudad es bonita." },
{ question: "fácil", answer: "簡単", description: "El ejercicio es fácil." },
{ question: "difícil", answer: "難しい", description: "El examen es difícil." },

{ question: "comer", answer: "食べる", description: "Quiero comer ahora." },
{ question: "beber", answer: "飲む", description: "Voy a beber agua." },
{ question: "vivir", answer: "住む", description: "Vivo en Tokio." },
{ question: "ir", answer: "行く", description: "Voy al trabajo." },
{ question: "venir", answer: "来る", description: "Ven aquí." },
{ question: "ver", answer: "見る", description: "Quiero ver la película." },
{ question: "hablar", answer: "話す", description: "Hablo español." },
{ question: "escuchar", answer: "聞く", description: "Escucho música." },
{ question: "leer", answer: "読む", description: "Leo un libro." },
{ question: "escribir", answer: "書く", description: "Escribo una carta." },

{ question: "estudiar", answer: "勉強する", description: "Estudio español." },
{ question: "trabajar", answer: "働く", description: "Trabajo en una empresa." },
{ question: "comprar", answer: "買う", description: "Quiero comprar pan." },
{ question: "querer", answer: "欲しい", description: "Quiero café." },
{ question: "tener", answer: "持つ", description: "Tengo un coche." },
{ question: "ser", answer: "〜である", description: "Soy estudiante." },
{ question: "estar", answer: "いる", description: "Estoy en casa." },

  { question: "variable", answer: "変数", description: "Esta variable guarda el nombre del usuario." },
  { question: "función", answer: "関数", description: "Esta función calcula el total." },
  { question: "array", answer: "配列", description: "El array contiene varios números." },
  { question: "condición", answer: "条件", description: "Si la condición es verdadera, se ejecuta el código." },
  { question: "bucle", answer: "ループ", description: "El bucle repite la operación varias veces." },
  { question: "error", answer: "エラー / バグ", description: "Hay un error en el código." },
]